### ISSUE TITLE
Invalid JSON returned from the API

### ISSUE THREAD

**Issue by planemad** [mapbox/mapbox-upload#56] opened 2015-12-17 20:48 UTC
Got this rather strange error while uploading a tiff

> Uploaded 96%
> Uploaded 100%
> Uploaded 100%
> Error: Invalid JSON returned from Mapbox API: Unexpected token <

**Comment by planemad** [comment] 2015-12-17 20:50
the tiff had an incorrect projection

**Comment by jflasher** [comment] 2016-02-26 19:46
I see this occasionally as well. Looks like it's coming from https://github.com/mapbox/mapbox-upload/blob/master/index.js#L180 or https://github.com/mapbox/mapbox-upload/blob/master/index.js#L67. I assume it's because the body is getting returned as HTML? Is there a common reason why this happens? Trying to figure out how to handle it downstream.

**Comment by mapsam** [comment] 2016-12-16 23:51
Hey @planemad @jflasher! If you can reproduce please send along a test case. It'd be great to test out the response code from the server to dig into this. Typically HTML is returned when credentials are invalid, which is my current hunch.

**Comment by jflasher** [comment] 2016-12-19 16:19
@mapsam I don't work on the project anymore, but @drewbo would be able to let you know if it pops up again.

**Comment by drewbo** [comment] 2016-12-19 18:18
Haven't seen this recently but I'll definitely post if it comes up again

**Comment by mapsam** [comment] 2016-12-21 06:19
Excellent. Going to close this now, as I'm unable to recreate. Feel free to re-open if it comes up again.

**Closed by mapsam** 2016-12-21 06:19 UTC
